# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: edoll <edoll@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/11/07 15:19:23 by edoll             #+#    #+#              #
#    Updated: 2019/11/07 16:44:41 by edoll            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FUNCTIONS = map_func \
			solving_func
# OBJ = $(patsubst %,%.o,$(FUNCTIONS))
SRC = $(patsubst %,%.c,$(FUNCTIONS))
CC = gcc
CFLAGS = -Wall -Wextra -Werror
HEAD = 
