#!/bin/bash
USER=$1
pgrep -u $USER | while read PID; do sudo pkill -9 $PID; done
/sbin/userdel -f $USER
echo "Human users on the system now:"
cat /etc/passwd | awk -F':' '{if ($3 >= 1000 && $3 < 30000) print $1}'